### ISSUE TITLE
Feature request: Fullscreen button

### ISSUE THREAD

**Issue by Go1den** [blakevanlan/KingdomCreator#104]
As a Dominion fan with lots of newbie friends, it would be nice to have a fullscreen mode which just displays the "main" div at 100% width and 100% height while hiding the sidebar, improving the readability of each card. Maybe when in full screen mode there would be another button to return to normal.

I like to display this website on my TV while playing so other players can look at the TV screen to see what the cards do without having to fidget with all the cards on the board.

**Comment by blakevanlan** [comment]
That's an interesting idea! I'll think on how to make it work universally. 

Thanks for the suggestion 😄

**Comment by Go1den** [comment]
Thanks! I'd do it myself but ashamedly my typescript and Vue knowledge is lacking.

Just in the browser itself I can edit the HTML to sort of accomplish it:
I just set the "sidebar" div to style="display: none;" and I set the "main" div to style="width: 100%; height: 100%;" if that helps.

**Comment by gillesgros** [comment]
Hello see on 71yeti.fr if that fits your need

**Comment by gillesgros** [comment]
deployed
