### ISSUE TITLE
Add Allies

### ISSUE THREAD

**Issue by dmi3kno** [blakevanlan/KingdomCreator#105]
New set is out. Maybe could be addressed together with Seaside 2ed, which should be made public within 2 weeks

**Comment by CaveCenam** [comment]
I agree. I am owning the game for weeks now and have been playing online with it. But I want to randomize my deck with your website, since it offers convenient options.

**Comment by blakevanlan** [comment]
Hi @dmi3kno and @CaveCenam - I hear you! I've started a branch to add support for Allies but I ran out of time before getting it done. Hoping to have it out in the next few weeks. Sorry for the delay!

**Comment by CaveCenam** [comment]
Good afternoon, i can participate for the German side of things, and have
time atm . therefore, if i can help, let it know. i could implement the
cards. (if instructed )

Am So., 1. Mai 2022 um 16:54 Uhr schrieb Blake VanLandingham <
***@***.***>:

**Comment by ghostsquad** [comment]
Please sir, may I have another [expansion]?

**Comment by gillesgros** [comment]
Hello,

I just proposed a pull request related to Allies.
You can see it working at : [https://71yeti.fr](https://71yeti.fr)

**Comment by dmi3kno** [comment]
Well done. Isnt Allies listed twice now (3rd and last entry)?

**Comment by gillesgros** [comment]
I will need to work on that. I'll post when done

**Comment by blakevanlan** [comment]
Done! #111

**Comment by theshampooguy** [comment]
The whole randomizer stopped working once Allies was introduced (no cards
work in the randomizer anymore).
