### ISSUE TITLE
Add/Update Seaside II

### ISSUE THREAD

**Issue by Pugintv** [blakevanlan/KingdomCreator#112]
See full notes: https://store.steampowered.com/news/app/1131620/view/3185745740382652293?fbclid=IwAR3AOMk-DcRkgFmUkKiv9nnOX7WFtMGr7z9y5F6McRQ8624JnrXb9iixY50

Changelog is as follows

- Added Astrolabe
- Replace Embargo for Blockade
- Replace Ghost ship for Monkey
- Replace Navigator for Tide Pools
- Replace Sea Hag for Sea Witch
- Replace Pearl Diver for Sea Chart
- Replace Explorer for Pirate
- Replace Pirate Ship for Corsair
- Replace Ambassador for Sailor

**Comment by Pugintv** [comment]
[seaside-2.yml.txt](https://github.com/blakevanlan/KingdomCreator/files/9124154/seaside-2.yml.txt)

**Comment by markbrockettrobson** [comment]
https://github.com/blakevanlan/KingdomCreator/pull/114
waiting on @blakevanlan

**Comment by RoothDragon** [comment]
Yes please. 👍

**Comment by gillesgros** [comment]
You can take a look at www.71yeti.fr it added

**Comment by gillesgros** [comment]
deployed
