### ISSUE TITLE
Please add Hinterlands II

### ISSUE THREAD

**Issue by noscgag** [blakevanlan/KingdomCreator#129]
The physical cards have been available for a while and I enjoy playing with them. Thanks.

**Comment by markbrockettrobson** [comment]
https://github.com/blakevanlan/KingdomCreator/pull/116

the Pr is done and waiting on blakevanlan

**Comment by gillesgros** [comment]
You can take a look at www.71yeti.fr it added

**Comment by noscgag** [comment]
Works great, thank you! 

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 18, 2022 at 4:35, ***@***.***> wrote:   


You can take a look at www.71yeti.fr it added

**Comment by gillesgros** [comment]
deployed
