### ISSUE TITLE
Add set label on recommended kingdom page

### ISSUE THREAD

**Issue by gillesgros** [blakevanlan/KingdomCreator#13]
When browsing thru recommended set, it would be nice to have, as  on the randomizer page the label indicating to which set the card is belonging.

I do not know yet enough  reactJs to fullfill this.

Thanks in considering this request.

**Comment by blakevanlan** [comment]
👍 Good idea. I'll make that change.

**Comment by blakevanlan** [comment]
Recommended kingdoms now have the labels:
![image](https://user-images.githubusercontent.com/987656/64912431-3a9dc980-d6fd-11e9-9c7b-291a70433439.png)

**Comment by gillesgros** [comment]
Well Done.
Thanks !
