### ISSUE TITLE
Give access to rules pdf

### ISSUE THREAD

**Issue by gillesgros** [blakevanlan/KingdomCreator#14]
Is it possible to add a page with sets list on the right side an on the left a display of the selected pdf rule.

By the way you are missing teh 2 following rules files 

Dominion 2nd ed : http://riograndegames.com/getFile.php?id=2011
Intrigue 2nd ed :  http://riograndegames.com/getFile.php?id=2012

**Comment by blakevanlan** [comment]
Thanks for the suggestion! I'll hopefully to get it this weekend 😄

**Comment by blakevanlan** [comment]
Added a new page for rules and included the 2nd edition rules. Sorry that it's ugly...

**Comment by gillesgros** [comment]
Great !
You did it fast. It is possible to keep the top menu instead of loading the pdf on the full page ?

**Comment by gillesgros** [comment]
To make it nicer you could go for something like this
![Image1](https://user-images.githubusercontent.com/39326434/64928094-a83c1980-d813-11e9-870e-d1e53ea93ddd.png)

**Comment by gillesgros** [comment]
Hello,

I am  not at all familiar with github.
I have multiple proposal for modification of your work for you to include,
if you like it.
 - a nice page for rules with boxes image
 - an addition of sets (containing only the additional cards for the
baseset and intrigue. there are called baseset (Add 2nd) and intrigue (Add
2nd)
 - I have made some fixes in the recommended kingdoms and integrated the
ones from baseset2 and intrigue2
 - As I have most of the cards in french, I have added the possibility to
switch the card from French to English.

I still have some more ideas that I will try.

It was quite a challenge, because I was not at all knowing Vue.js. A really
cool language that gives quite a large number of possibilities.

You can  have a look at http://71yeti.fr

If you wan I can send a zip to you.
Or I will try to understand how to make a pull request on github.

Regards

Gilles

**Comment by blakevanlan** [comment]
Love the enthusiasm! I've had a busy week so I don't think I'm actually going to have time to look at any of these until this weekend, but hopefully I can get some of these improvements added to the site. 

Cheers!
