### ISSUE TITLE
Plunder

### ISSUE THREAD

**Issue by markbrockettrobson** [blakevanlan/KingdomCreator#142]

**Comment by markbrockettrobson** [comment]
HI i

I Have had problems finding time to work on this for the last handful of weeks but I am back at it and have set some time aside this weekend. 

I am making this Issue to allow a space to communicate.

**Comment by gillesgros** [comment]
Added 1 comment in PR.
Looks good to me so far.

**Comment by markbrockettrobson** [comment]
https://github.com/blakevanlan/KingdomCreator/pull/144

PR ready to go

**Comment by gillesgros** [comment]
Trait should be lnk to a kingdom.
it should be the same as for Obelisk (empires)

**Comment by gillesgros** [comment]
OK I did th deployement.

I also created a branch "NewfeaturesGilles" including multiple changes.
Can you have a look and tell me your feeling.

**Comment by gillesgros** [comment]
deployed
