### ISSUE TITLE
Some sets are listing with II some with (2nd) to note second edition We should fix that 

### ISSUE THREAD

**Issue by markbrockettrobson** [blakevanlan/KingdomCreator#143]
<img width="83" alt="image" src="https://user-images.githubusercontent.com/47262668/214314850-0644bbc8-9d06-43f7-89f0-5106790d2fbc.png">

**Comment by gillesgros** [comment]
Hello.

What is prefered in english
  Dominion II or Dominon (2nd)

**Comment by markbrockettrobson** [comment]
Hi
I don't mind and am happy to go with what ever you like

**Comment by gillesgros** [comment]
fixed on master and deplyed
