### ISSUE TITLE
Options are badly aligned on mobile view. 

### ISSUE THREAD

**Issue by rPraml** [blakevanlan/KingdomCreator#146]
Since the last update, the options for "1st" and "2nd" are badly aligned. See screenshot:
![Screenshot_20230129_175756_Chrome](https://user-images.githubusercontent.com/5530228/215343188-8eeba5e2-3b35-45ca-be54-4d522ac169c3.jpg)

Roland

**Comment by gillesgros** [comment]
fixed and deployed

**Comment by gillesgros** [comment]
Deploy failed

**Comment by gillesgros** [comment]
deployed
