### ISSUE TITLE
Allow Customization for the Events, Ways, and Landmarks section

### ISSUE THREAD

**Issue by KasDev573** [blakevanlan/KingdomCreator#164]
Allow for a setting to change the number of ways, events, landmarks. I personally play with a group that does 2 events, 1 way, and 1 landmark per game and it is quite fun. It would be great if I could customize that section of the randomizer, currently, all I can see is that it randomly picks 2 from all of those categories.

**Comment by gillesgros** [comment]
I will consider this in building a setup page

**Comment by gillesgros** [comment]
Can you provide a concept of UI ?
I am working on a new screen for settings

**Comment by gillesgros** [comment]
Have a look at work in progress at www.71yeti.fr

**Comment by KasDev573** [comment]
Looks great! It looks like the base action supply piles being increased
works well. One issue I am seeing is that I have my settings at 4 addons.
Breaking it down into 2 events, 1 landmark, and 1 way. Despite this,
assuming I configured it correctly (I attached a screenshot to of
my settings), it doesn't always work and feels random. Sometimes I get 3 of
one of those cards, then 1 of another category, or 2 sets of 2 of those
options.

**Comment by gillesgros** [comment]
Differentiation between addons is not yet working.
I will keep you posted

Le mar. 16 juil. 2024 à 23:36, KasDev573 ***@***.***> a
écrit :

> Looks great! It looks like the base action supply piles being increased
> works well. One issue I am seeing is that I have my settings at 4 addons.
> Breaking it down into 2 events, 1 landmark, and 1 way. Despite this,
> assuming I configured it correctly (I attached a screenshot to of
> my settings), it doesn't always work and feels random. Sometimes I get 3
> of
> one of those cards, then 1 of another category, or 2 sets of 2 of those
> options.
>

**Comment by gillesgros** [comment]
A new release to test.
Tell me what you think

**Comment by gillesgros** [comment]
feature added in 6.3.0 release
