### ISSUE TITLE
Additional Cards such as Colonies/Platinum or Shelters are not displaying correctly

### ISSUE THREAD

**Issue by scottroper** [blakevanlan/KingdomCreator#166]
Clicking Randomize while allowing Prosperity for Colony/Platinum or Dark Ages for Shelters will correctly select these additional cards some of the time as seen in the URL. However, the graphical display for the Additional Cards does not update.

Steps to reproduce:
1. Select only Prosperity and Dark Ages for the expansions.
2. Note the graphical display for Additional Cards.
3. Click Randomize. The display for Additional Cards will not update even if the URL now shows colonies=1 or shelters=1.

Refreshing the page will correctly update the graphical display.
![Capture](https://github.com/user-attachments/assets/d9f6eb53-d65c-4735-a2ae-37dcdb9e738a)

**Comment by gillesgros** [comment]
fix in 6.2.0 release
