### ISSUE TITLE
The content displayed differs from the query parameters

### ISSUE THREAD

**Issue by Liala1** [blakevanlan/KingdomCreator#167]
When I accessed the previously generated URL, a different kingdom was drawn.
Upon investigation, it seems that cards not in the currently selected set are being reselected.
In older versions, query parameters took precedence, which I think was more convenient.

**Comment by gillesgros** [comment]
fix in 6.3.0 release

**Comment by gillesgros** [comment]
Hello release 6.4.2 should allow you to recall old kingdoms
