### ISSUE TITLE
Bug: Copy does not work anymore like it used to

### ISSUE THREAD

**Issue by rubikscuber** [blakevanlan/KingdomCreator#169]
The copy function at the bottom of the page does not work as it used to. The names of the copied cards are not translated anymore. Also, if the site is embedded in an iframe, the copy does not work at all. (`TypeError: navigator.clipboard is undefined`)

**Comment by gillesgros** [comment]
Can you give me more detail on the problem ?
I am not getting the issue

**Comment by rubikscuber** [comment]
When I click on the copy button - 
![grafik](https://github.com/user-attachments/assets/781e7708-8690-485f-ac30-6df5f9c80477)
the cards were copied in the language that was is selected (e.g german) - however, now the internal names of the cards seem to be copied (which are in English and in a different format "extension_cardname" (baseset_festival, baseset_remodel,...)).

In the case, the generator is included in an iframe - the copy does not work at all and is showing the TypeError in the js console.

**Comment by gillesgros** [comment]
Thanks for the clarification. I will look into it

**Comment by gillesgros** [comment]
Fix in release 6.3.1

**Comment by rubikscuber** [comment]
Nice! Thank you very much

**Comment by rparkchan** [comment]
Hi, this appears to be broken again, copy string button yields i.e. "adventures_amulet" style strings rather than "amulet" making it difficult to import into Dominion online

**Comment by gillesgros** [comment]
Regression  confirmed. Should be ok
