### ISSUE TITLE
When randomizing "Young Witch" no bane card set

### ISSUE THREAD

**Issue by gillesgros** [blakevanlan/KingdomCreator#17]
When randoming , a game with the young witch, no bane card is defined.

**Comment by gillesgros** [comment]
I almost fix the display on the set page.
I will propose soon a new pull request.

**Comment by blakevanlan** [comment]
Yes, this has been a long standing thing I've been meaning to get done. I think the way it should be implemented is capturing all the `availableCards` from each supply division after creating a kingdom supply then using that pool of cards to pick a bane card.

I was thinking about adding bane cards this weekend but if you're going to give it a shot then I'll focus on adding boons for Druid instead.

Thanks!

**Comment by gillesgros** [comment]
I don't know if I have yet catch how randomize work.
I will try to give it a shot.

I keep you posted.

Gilles

**Comment by gillesgros** [comment]
I have been trying big time this week. I was not able to make it work and being rendered.
I think you should give it a shot.
It is above my current knowledge of the language and the algorithm implemented.

Regards.

**Comment by blakevanlan** [comment]
Thanks for the effort! Yeah, apologies for it all being more complicated than I would have liked.

I've got a packed weekend so I don't think I'll be able to get a chance to review your PR this weekend but I'll do my best to get to it early next week.

Cheers!

**Comment by gillesgros** [comment]
Do it at your pace.
I will keep trying understanding the bane problem.
If by any luck I can make it work I will propose PR

Regards

**Comment by gillesgros** [comment]
After spending some (good) time on it, I think I made it work.
I need some more testing. I will submit a PR soon.

**Comment by gillesgros** [comment]
Hi,

I updated the PR with the bane card selection.
Tell me what you think of this.

I am working on different things You can see some at https://71yeti.fr

I am working on some more features (the first set should be done)
 - allow french card and rule display
 - fixing the enlarge button on kingdoms and rules
 - completion of kingdoms based on the available rules
 - Add a banner to ease kingdoms navigation
 - adding a set page to display all cards of a set

- display all recommended kingdoms and filter thru it based on set
- allow saving of some personnal sets.
- use more correctly the screen size (more than 5 cards displayed or
larger) or allow enlarge also

Regards

Gilles

**Comment by gillesgros** [comment]
It is nor working for me
