### ISSUE TITLE
Suggestion: Probability slider for cards in owned expansions

### ISSUE THREAD

**Issue by SebastianHira** [blakevanlan/KingdomCreator#178]
Currently you cannot deselect any specific cards whatsoever. This makes playing with the promo addon specifically challenging, because most of the time it selects promos you don't have.

An interface for each expansion with every card having a slider to modify probabilities would be nice and would solve this issue at the same time. 
A slider all the way to the left would turn off that card (x0), the middle would be x1 and the right could be x2 odds, with .1 steps in between.
This way not only can you deselect any card you dislike, you can also skew the randomization towards liked cards a little.

**Comment by gillesgros** [comment]
feature included in release 6.4.2
