### ISSUE TITLE
Sea hag bug

### ISSUE THREAD

**Issue by BertscheS** [blakevanlan/KingdomCreator#30]
The sea hag shows as 2 gold instead of 4 when the result of 10 cards is shown. Please also verify if this is just an ordering issue or if the algorithm really thinks it picked a 2 gold costing card.
![Screenshot_20200226-181751](https://user-images.githubusercontent.com/61513934/75369847-7cde5000-58c4-11ea-99b1-a7eaba772b98.png)

**Comment by blakevanlan** [comment]
@BertscheS This is now fixed. Thanks for the report!

**Comment by BertscheS** [comment]
I can confirm it is fixed. Thanks!
