### ISSUE TITLE
Caravan Cost Bug

### ISSUE THREAD

**Issue by BertscheS** [blakevanlan/KingdomCreator#34]
Hi, I reviewed your yaml files for correct card costs in the Base set, Intrigue set, Seaside set and Prosperity set. I only found one more bug, which is Caravan in Seaside. It should have a cost of 4, but in your code it is 5.

**Comment by blakevanlan** [comment]
Hi @BertscheS, thanks for taking the time to audit those sets! I'm on vacation for a week but will get this fixed up once I'm back.

**Comment by BertscheS** [comment]
Thanks! :)
