### ISSUE TITLE
Card properties fix to apply

### ISSUE THREAD

**Issue by gillesgros** [blakevanlan/KingdomCreator#35]
Hello,

Here are some fixes to apply in sets folder

Intrigue & Intrigue2
   **Swindler** : **isAttack** should be **true**

Seaside
   **Lighthouse** : **isReaction** shoule be **false**

Hinterlands
**Haggler** : cost should be **5** not 4
**Cache** : cost should be **5** not 4

Darkage
   **Count** : **isTreasure** should be **false**

Adventures
   **Coin of the realm** : **isTreasure** should be **true**

Empires
   **Legionary** : cost should be **5** not 8

Nocturne
   **Monastery** : **isDuration** should be **false**
   **Ghost Town** : **isDuration** should be **true**
   **Den of Sin** :  **isDuration** should be **true**
   **Vampire** : **isAction** should be **false**
   **Blessed Village** : **isFate** should be **true**
   **Skulk** : **isFate** should be **true**

**Comment by blakevanlan** [comment]
Wow thanks for all the time auditing those cards!!
