### ISSUE TITLE
To add the possibility to track which Game i have played

### ISSUE THREAD

**Issue by gillesgros** [blakevanlan/KingdomCreator#40]
Hello,
A nice new feature to consider.
On a browser, it would be nice to be able to store an so track which recommended set of kingdom I have played.

My suggestion to make it simple, when you change browser (cookies reset) you lost the tracking.

What do you think.

If you feel that might be good I will try it during my covid confinement.

Gilles

**Comment by blakevanlan** [comment]
Sure, sounds like a good feature. I'd be happy to have it added to the site.

I've been trying to come up with a way to easily store this kind of info across devices without running a backend server. One option would be to allow people to sign in via Google OAuth then use a Google Sheet as a backend. That way all this data could be persisted. What do you think?

**Comment by gillesgros** [comment]
Hello, 
yes using Goggle Oauth is a great way and we might alsouse it to allow personnal sets to be stored.

**Comment by gillesgros** [comment]
I build a version which use only client side storage.
Tell me what you think of it.
I tryed to play with Google Oauth but I feel it request a too large access of the google drice of the user.
I will try it on my side if needed.

Tell me what you think of it.

Regards

**Comment by mindgam3s** [comment]
> I build a version which use only client side storage.
> Tell me what you think of it : https://www.71yeti.fr
> I tryed to play with Google Oauth but I feel it request a too large access of the google drice of the user.
> I will try it on my side if needed.

I think you should just create a Pull Request and let him see whether he likes it :)
this really looks interesting

also I noticed you implemented some "animations" when re-ordering the selected cards ?
really liked that

**Comment by mindgam3s** [comment]
> I build a version which use only client side storage.
> Tell me what you think of it : https://www.71yeti.fr
> I tryed to play with Google Oauth but I feel it request a too large access of the google drice of the user.
> I will try it on my side if needed.

@gillesgros 

I think you should just create a Pull Request and let him see whether he likes it :)
this really looks interesting

also I noticed you implemented some "animations" when re-ordering the selected cards ?
really liked that

**Comment by gillesgros** [comment]
deployed on brower basis
