### ISSUE TITLE
make the "Alchemy" rule optional

### ISSUE THREAD

**Issue by mindgam3s** [blakevanlan/KingdomCreator#48]
It would be great to make the Alchemy rule optional, meaning that it's not always at least 3 alchemy cards or none.

**Comment by blakevanlan** [comment]
@mindgam3s: You're right, you should be able to toggle this on and off. I'll try to find some time this weekend to add an option.

Thanks for filing!

**Comment by mindgam3s** [comment]
Hi,

I just wanted to ask how the status is.

**Comment by blakevanlan** [comment]
Hi,

I've been slow. 😞 

Really was hoping to get to this the past to weekend and wasn't able to find the time. In the middle of switching jobs and moving across the country so life's been a bit too hectic to find the time to make this happen. Sorry!

It's definitely the top improvement on my list!

**Comment by mindgam3s** [comment]
bump ?^^

**Comment by blakevanlan** [comment]
@mindgam3s Your wish is my command! (after an absurdly long wait, of course)

**Comment by mindgam3s** [comment]
thank you!
