### ISSUE TITLE
Does not work in gecko browsers

### ISSUE THREAD

**Issue by revad** [blakevanlan/KingdomCreator#5]
See https://together.jolla.com/question/183247/bug-missing-feature-on-sailfish-os-browser/

The Jolla browser is gecko-based. It doesn't work in Firefox desktop or Android (v59) either.

(revad = DaveRo)

**Comment by blakevanlan** [comment]
Thanks for bring this to my attention! I've pushed a change that looks like it fixes the primary problem but the animation still could use some work.
