### ISSUE TITLE
Missing Promo Cards

### ISSUE THREAD

**Issue by notevenodd** [blakevanlan/KingdomCreator#55]
Some cards are missing and/or never get selected, at least from Promo:
- Dismantle
- Captain,
- Church
- Summon (event)
- Sauna+Avanto (split pile) [there are "promos_sauna" and "empires_saunaavanto" images though]

**Comment by TArtzo** [comment]
This! If this is a problem for you I suggest using Jack of All Dominion on Android if this still isn't fixed. I run it on my computer using BlueStacks.

**Comment by blakevanlan** [comment]
@TArtzo, @notevenodd - Finally got around to fixing this. Apologies that it took so long!

**Comment by TArtzo** [comment]
> @TArtzo, @notevenodd - Finally got around to fixing this. Apologies that it took so long!

Appreciate it! But just wanted to point out that Avanto and Sauna are a split deck. Currently they're showing up separately.
