### ISSUE TITLE
Duplicate query parameters breaks site

### ISSUE THREAD

**Issue by davidtorosyan** [blakevanlan/KingdomCreator#66]
Visit this url:
https://dominionrandomizer.com/?supply=&supply=

And you'll find a mostly empty page with this error in the console:
`TypeError: t.split is not a function`

Apparently the [RFC](https://tools.ietf.org/html/rfc3986#section-3.4) doesn't mention how to handle duplicate query parameters (see discussion [here](https://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys)), but it would probably be good not to fail.

**Comment by gillesgros** [comment]
fix commited waiting for deploy
