### ISSUE TITLE
Landmarks aren't generated if the query parameters have supply cards

### ISSUE THREAD

**Issue by davidtorosyan** [blakevanlan/KingdomCreator#67]
This is kind of an obscure (bug?), but that's what you get when you're working on edge cases.

#### Setup
Uncheck all options except for Empires.
#### Happy path
Visit https://dominionrandomizer.com/ and notice two landmarks get generated.
#### Bug
Visit https://dominionrandomizer.com/?supply=archive and notice that while the rest of the supply is filled out, the landmarks stay empty.

### Is this a bug?
It's hard to think of how this would impact the user experience, but it seems unexpected to me, so I thought I'd raise it in case this wasn't intended.

**Comment by gillesgros** [comment]
deployed
