### ISSUE TITLE
Feast card error in french version

### ISSUE THREAD

**Issue by Dukesavard** [blakevanlan/KingdomCreator#78]
In french version "Festin" should be 5 not 2

**Comment by blakevanlan** [comment]
You're totally right! Not sure how that image was created incorrectly. I'm not able to find the French version of that card with the correct cost. I'll replace it as soon as I find it.

**Comment by gillesgros** [comment]
Hello,

Here is a fix French card 
![feast](https://user-images.githubusercontent.com/39326434/113779477-15810980-972e-11eb-8305-4b171b64dcbd.jpg)
