### ISSUE TITLE
Add Sort By Cost

### ISSUE THREAD

**Issue by kasuinc** [blakevanlan/KingdomCreator#8]
Could you possibly add a sort feature that sorts by kingdom card cost in ascending order?  Our group always sorts this way to aid in purchasing decisions. 

I am assuming the sort would look like:
- Sort by Cost on, Sort Alpha Off = cards sorted in ascending cost order, then default sort (is it expansion?) within the same cost
- Sort By Cost on, Sort Alpha On = cards sorted in ascending cost order, then sorted alpha within the same cost

**Comment by blakevanlan** [comment]
Good idea! Added an option to sort by set, alphabetical, and cost. Enjoy!

**Comment by kasuinc** [comment]
That is fantastic!  Thanks for such a quick turnaround!   I really like your application.
