### ISSUE TITLE
Various special card setup rules

### ISSUE THREAD

**Issue by berleant** [blakevanlan/KingdomCreator#82]
Some cards have second-order effects on the board set up, such as picking a Bane for Young Witch. Picking a Bane for Young Witch is already implemented. Some other similar situations, which I have attempted to order in terms of "fit", are:

* Obelisk chooses an action supply pile http://wiki.dominionstrategy.com/index.php/Obelisk
  * A great fit for this project, especially since it's very similar to selecting a Bane for Young Witch. A card cover similar to Bane would work well.
  * Can one action supply pile be both Bane and Obelisk?
* Way Of The Mouse chooses an unused action http://wiki.dominionstrategy.com/index.php/Way_of_the_Mouse
  * Another great fit for this project, also very similar to selecting Bane.
  * The main sticking point might be how to display the result such that it's clearly not in the Supply (unlike Young Witch/Bane and Obelisk).
* Platinum and Colony have a chance of being used according to the proportion of cards from Prosperity in the kingdom http://wiki.dominionstrategy.com/index.php/Platinum
  * Another good fit for the project, since the suggested procedure involves using the randomizer deck.
  * How should this be displayed?
* Druid chooses three random Boons http://wiki.dominionstrategy.com/index.php/Druid
  * Implementing this is of questionable usefulness, since picking random Boons is very simple to do irl: draw the top 3 cards of the Boon deck (which has already been shuffled during set up)

**Comment by blakevanlan** [comment]
Thanks for the suggestions! Comments inline below:

> Obelisk chooses an action supply pile

Great point! This should be reasonable to do.

> Way Of The Mouse chooses an unused action

Make sense. Should work very similar to how bane is handled.

> Platinum and Colony have a chance of being used according to the proportion of cards from Prosperity in the kingdom

This works already! It shows up at the bottom which is easy to miss.

> Druid chooses three random Boons

This one is supported too.

**Comment by gillesgros** [comment]
added and deployed
