### ISSUE TITLE
Merge Promo cards "Avanto" and "Sauna"

### ISSUE THREAD

**Issue by TArtzo** [blakevanlan/KingdomCreator#84]
Both of these decks are part of a split deck normally, similar to Catapult/Rocks or Settlers/Bustling Village. I suggest Avanto should be deleted and the image for Sauna should be replaced with the randomizer card that references them both.

Here's a scan: http://wiki.dominionstrategy.com/images/thumb/4/4a/Sauna_Avanto.jpg/375px-Sauna_Avanto.jpg

**Comment by blakevanlan** [comment]
Great catch, totally didn't read closely enough and don't have the cards myself!
