### ISSUE TITLE
Copy cards list to clipboard

### ISSUE THREAD

**Issue by DavidGasku** [blakevanlan/KingdomCreator#9]
This would allow to paste the cards list to dominion.games, so you can play several games with the same kingdom.
Thanks for this great webpage!

**Comment by blakevanlan** [comment]
Hi David!

Great suggestion. It looks like https://dominion.games supports copying and pasting using a comma separated list in the "Enter cards to include in your kingdom" box.

You can pretty much get this to work today by pulling the cards from the URL:
`
https://dominionrandomizer.com/?supply=chapel,councilroom,festival,gardens,merchant,militia,moat,remodel,vassal,witch
`

But you'd need to add spaces if any exist (like council room in this example):

`
chapel,council room,festival,gardens,merchant,militia,moat,remodel,vassal,witch
`

I'll look at adding a dedicated button!

**Comment by stefprez** [comment]
This would also be particularly helpful for pasting different curated sets into https://dominion.games as well.

**Comment by blakevanlan** [comment]
Sorry this fell off my radar. I'll try and get it done this weekend!
